manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: as29
      url-base: https://github.com/as29
  projects:
    - name: zmk
      #remote: zmkfirmware
      #revision: main
      remote: infused-kim
      revision: split-encoder
      import: app/west.yml
  self:
    path: config
